name: pub_stats
description: >
  A library useful for applications or for sharing on pub.dartlang.org.
version: 0.0.1
author: Jim Simon <jim.j.simon@gmail.com>
#homepage: https://www.example.com
dependencies:
  polymer: "0.15.5+4"
  shelf_route: ">=0.12.0 <0.13.0"
  shelf_static: ">=0.2.2 <0.3.0"
  core_elements: ">=0.6.0+4 <0.7.0"
  app_router: ">=0.1.1 <0.2.0"
  managed_mongo: ">=1.1.3 <2.0.0"
  mongo_dart: ">=0.1.45 <0.2.0"
  pub_client:
    path: "../pub_client/"
  dartson: ">=0.2.2 <0.3.0"
dev_dependencies:
  unittest: ">=0.11.5+4 <0.12.0"
transformers:
- polymer