name: pub_stats
description: >
  A library useful for applications or for sharing on pub.dartlang.org.
version: 0.0.1
author: Jim Simon <jim.j.simon@gmail.com>
#homepage: https://www.example.com
dependencies:
  polymer: any
  shelf_route: any
  shelf_static: any
  core_elements: ">=0.6.0+4 <0.7.0"
dev_dependencies:
  unittest: any
transformers:
- polymer